### ISSUE TITLE
BSoD after loading successfully.

### ISSUE THREAD

**Issue by wavedao** [armvirus/SinMapper#4]
![crash2](https://user-images.githubusercontent.com/20006303/213527578-c2fa9286-b93b-46e2-853d-071a50b34953.jpg)

system is win10 21H2.  It maps the driver correctly. But will lead to crash on any reboot and sometimes installing new software after using.  Hard reset will boot and reboot without problem. But anytime after running code with this. It's BSoD as the attached picture. 
Any way to solve this?

**Comment by armvirus** [comment]
This project is old, and i don't plan to support it. use a vm and debug.
